spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL8Dialect
  database : mysql
  hibernate.ddl-auto : update